### ISSUE TITLE
FQDN, hostname and vm-id - confusion

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/dns-release#17]
Hi all,
we have been using bosh with local-dns enabled now in our local dev environments and the staging environment as well. During that we have discovered something we want to clarify. 

After the deployment we were checking the spec details and they are as follows:

```json
{
  "id":"18c97e6e-7da1-4a98-9308-5e63826c26bc",
  "index":0,
  "az":null,
  "address":"18c97e6e-7da1-4a98-9308-5e63826c26bc.cephfs.default.cephfs.bosh"
}
```

This shows, that the `id` is the hostname of the `address`. Issuing `hostname` on the VM returns `3e4b1ea7-7e28-4691-8520-83a8e9848abf` instead.

Questions:
* Is this intended to be like that?
* If so, why to they differ?
* If so, what is the proper way to resolve the hostname?

Besides that: thanks a lot for the effort and work of this release. It really helps a lot!

**Comment by cppforlife** [comment]
> thanks a lot for the effort and work of this release. It really helps a lot!

awesome to hear!

> This shows, that the id is the hostname of the address. Issuing hostname on the VM returns 3e4b1ea7-7e28-4691-8520-83a8e9848abf instead.

`18c97e6e-7da1-4a98-9308-5e63826c26bc` is the instance id (shown in bosh instances). it ends up as the primary dns identifier for an instance. 

`hostname` of the machine is set by the bosh agent [1] to the agent id. agent id is more or less an internal identifier unique to a vm (changes as vms are recreated; instance id does not change). 

[1] https://github.com/cloudfoundry/bosh-agent/blob/430cddb3aa71138b7795a2568ff3cb3a68147cdb/agent/bootstrap.go#L88

> Is this intended to be like that?

yup.

> If so, why to they differ?

historic reasons mostly. there are good reasons for them to be "unrelated" though:
- dont have to worry about cross os differences
- prevents accidental hostname configuration (instead of explicitly using spec.address)

> If so, what is the proper way to resolve the hostname?

in your job erb templates, you should be able to use spec.address to get dns address for that job. would spec.address work in your use case?

**Comment by jheyl** [comment]
Thank's alot for your quick answer and the insights you gave us. 
Unfortunately this doesn't resolve our Problem.

We have to deploy a piece of Software which uses a Script to configure the other VMs of the Deployment based on SSH. It requires to be invoked with the actual hostname of the VM otherwise it fails creating software specific Keys. We don't have control over the Software so we couldn't change behaviour. 

We are currently thinking about possible solutions for the Problem, if you have any other idea we could try we would be very thankful. 

1. The hostname is specified in the /var/vcap/instance/dns/records.json file we could extract it and write it to the /etc/hosts with the corresponding IPs.

2. We could change the hostname of the VMs to match the DNS-Record. Is this a bad Idea? Does this interfere with any bosh routines or is this a save thing to do?

Thanks in advance.

**Comment by cppforlife** [comment]
> It requires to be invoked with the actual hostname of the VM otherwise it fails creating software specific Keys

it cannot use fqdn?

> ...based on SSH

is this for host key fingerprinting?

we are happy to video/audio conference to chat more about the particular use case. might be easier to come up with a solution.

**Comment by jheyl** [comment]
Hi, 
thank you very much for your help and the will to chat with us. We found a solution for our problem. We search for the hostname in the `var/vcap/instance/dns/records.json` file and write those hostnames with the corresponding ip to the /etc/hosts File. With this little trick we are able to feed the third Party Software with the Hostnames of the VMs. 

`HOSTNAMES=( $(cat /var/vcap/instance/dns/records.json | jq '.record_infos | .[] | {'host':.[11], 'id':.[12], 'deployment_name':.[8]}' | jq  -r --arg DEPLOYMENT "$DEPLOYMENT" 'select(.deployment_name==$DEPLOYMENT)' | jq --raw-output --slurp '.=sort_by(.id) | .[].host') )`

**Comment by cppforlife** [comment]
> We search for the hostname in the var/vcap/instance/dns/records.json

would you be able to use aliases instead? (http://bosh.io/docs/dns#aliases) for example in your job you can add dns/aliases.json that would include something like this:

```
<%=

aliases ={}
link("something-else").instances.each do |instance|
  aliases["something#{instance.index}"] = instance.address
end

JSON.dump(aliases)

%>
```

and then software can use `something1` for example to resolve instances.

**Comment by cppforlife** [comment]
@jheyl any thoughts on above comment?

**Comment by jheyl** [comment]
@cppforlife I'm sorry I forgot to answer to your really helpful answer. It turned out that we went down an other path with the problem we wanted to solve and ended up to use another piece of software. This was not related to our bosh-dns issue it was an architectural decision. 

Therefore we never checked wether your suggestion is going to work in our deployment. But it helped colleagues with an problem in an unrelated bosh-release where they are going to implement dns aliases in future versions. 

So thanks again for the tipp and all the support.
