### ISSUE TITLE
Removing bosh-dns job does not restore /etc/resolv.conf

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/dns-release#37]
Typically when removing bosh-dns Bosh does not recreate the VM. It removes the jobs files and restarts the VM. This means the file `/etc/resolv.conf` has the wrong contents. It should be restored to a default, or its original, form.

**Comment by beyhan** [comment]
This is a duplicate of https://github.com/cloudfoundry/bosh-dns-release/issues/34

**Comment by belinda-liu** [comment]
Hey @henrytk,

Thanks for pointing that out. As @beyhan mentioned, this is an issue tracked in #34. Not sure if you got a chance to read over that issue, but the gist is that we haven't prioritized it yet and a clear solution isn't readily available. Did you have any suggestions on how to fix this issue? 
If not, it may be more helpful if we could close this so that we can avoid duplicate github issues. What do you think?

**Comment by henrytk** [comment]
@belinda-liu closing this to avoid duplication of #34
