### ISSUE TITLE
reverse resolution on the ip

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/dns-release#40]
A question about bosh-dns. If I define an alias for an external machine, so pointing to a static ip address, is it possible to run a reverse resolution on the ip?

**Comment by pivotal-mp** [comment]
Hi @gu-bin,

That is outside of the control of BOSH-DNS. You might have to configure your internal reverse DNS service so that your static IP points to whatever internal hostname you want.

Since that static IP is not something BOSH-DNS is configured with, it should delegate all reverse lookups to whatever internal DNS you already have.

Does this answer your question? Difficult to give specific advice without knowing more about your internal setup.

Best,
@pivotal-mp && @dpb587-pivotal

**Comment by belinda-liu** [comment]
Hi @gu-bin,

We're closing this issue for now, but feel free to reopen if you have any further questions.

Thanks,
@belinda-liu && @pivotal-mp, CF BOSH team
