### ISSUE TITLE
[Feature request] Distribute health checks over the remote health interval

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/dns-release#58]
We observe that the `bosh-dns` server does all health checks, which are currently active at once. This  has the impact that the `bosh-dns` process produces CPU spikes, which can impact other processes on the same VM. It will be better to distribute the checks over the
[remote_health_interval](https://github.com/cloudfoundry/bosh-dns-release/blob/835f0373a33db476f173e37544e7e9e61861d52b/jobs/bosh-dns/spec#L147).

**Comment by cjnosal** [comment]
One option that might help is to set the HealthFilter/HealthWatcher work pool size in the job spec. When adjusting the value it would be important that the work pool can get through all requests before `remote_health_interval`, otherwise a backlog would accumulate.

https://github.com/cloudfoundry/bosh-dns-release/blob/master/src/bosh-dns/dns/main.go#L145
https://github.com/cloudfoundry/bosh-dns-release/blob/master/src/bosh-dns/dns/server/records/health_filter.go#L40

Triggering health checks at different times (instead of triggering everything on one timer) could work but will likely involve more complexity.

I don't have access to large environments to verify change in cpu load these changes would hopefully offer, so I'd appreciate it if you could prove that out.
